DATA_DIR = "data"
UNITS = {
        "wacc":  "%", 
        "scores": "",
        "factory_utilization": "%",
        "employee_engagement": "%",
        "interest_coverage": "x",
        "marketing_spend_rev": " USD",
        "e_cars_sales": " units",
        "co2_penalty": "M (USD)"
}      
KPIS = {
    "wacc": "WACC",
    "scores": "Scores",
    "factory_utilization": "Factory Utilization",
    "employee_engagement": "Employee Engagement",
    "interest_coverage": "Interest Coverage",
    "marketing_spend_rev": "Cumulative Marketing Spend/Rev",
    "e_cars_sales": "eCars Sales",
    "co2_penalty": "CO2 Penalty"
} 
TEAM_NAMES = [
    "fovro", 
    "Fastun", 
    "Nyxx", 
    "CarSpa", 
    "Motion", 
    "Worthwheel", 
    "Carzio", 
    "Rollovo", 
    "iAuto", 
    "VroomTime", 
    "Kar", 
    "EliteTechs",
    "Carz",
    "MileMode",
    "Automotiq",
    "RYDI", 
    "EvolutionAuto",
    "Automovo",
    "ROBOH",
    "rimovo",
    "ottobi",
    "Evi",
    "Rusted",
    "Cjio",
    "NitroRide",
    "HXH",
    "SpeedLabs",
    "TenQ",
    "Caraxa",
    "Blazers",
    "DriveSwitch", 
    "GIIQ", 
    "Teuso",
    "Hoqa", 
    "AutoInfinite", 
    "vusk", 
    "DentCenter", 
    "Turbo", 
    "evCU", 
    "Electronically", 
    "Drivat", 
    "Torque", 
    "Drift", 
    "Carvato", 
    "Rush", 
    "Matic", 
    "Wheelic", 
    "Slidyn", 
    "Pitpo", 
    "caralo", 
    "Drivesly", 
    "Xuad", 
    "CarLeap", 
    "Tazox", 
    "Amxu", 
    "Honkli"
    ]
TEAMS = {}
for i in range(len(TEAM_NAMES)):
    TEAMS[i + 1] = TEAM_NAMES[i]